CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  username UNIQUE TEXT NOT NULL,
  password TEXT NOT NULL,
  is_member boolean DEFAULT FALSE,
  is_admin boolean DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS messages (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  timestamp timestamp NOT NULL,
  user_id REFERENCES users (id) ON DELETE CASCADE NOT NULL
);
